# Generated by Django 4.2.9 on 2024-02-24 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerifyCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="验证码"),
                ),
                ("email", models.EmailField(max_length=50, verbose_name="邮箱")),
                (
                    "send_type",
                    models.CharField(
                        choices=[("register", "注册"), ("forget", "找回密码")],
                        max_length=10,
                    ),
                ),
                (
                    "send_time",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024,
                            2,
                            24,
                            15,
                            23,
                            38,
                            245083,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
            ],
            options={
                "verbose_name": "邮箱验证码",
                "verbose_name_plural": "邮箱验证码",
            },
        ),
    ]
