# Generated by Django 4.2.9 on 2024-02-24 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_emailverifycode"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emailverifycode",
            old_name="send_type",
            new_name="motive",
        ),
        migrations.AlterField(
            model_name="emailverifycode",
            name="code",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="验证码"
            ),
        ),
        migrations.AlterField(
            model_name="emailverifycode",
            name="send_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
