# Generated by Django 4.2.9 on 2024-02-24 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_rename_send_type_emailverifycode_motive_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emailverifycode",
            old_name="code",
            new_name="captcha",
        ),
    ]
