# Generated by Django 4.2.9 on 2024-03-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_rename_code_emailverifycode_captcha"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="about",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
