# Generated by Django 4.2.9 on 2024-03-06 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_about"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailverifycode",
            options={
                "verbose_name": "EmailCaptchas",
                "verbose_name_plural": "EmailCaptchas",
            },
        ),
    ]
