# Generated by Django 5.0.4 on 2024-04-21 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20240329_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='dark', max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('zh', '简体中文')], default='en', max_length=20)),
                ('timezone', models.CharField(default='Asia/Shanghai', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserSettings',
                'verbose_name_plural': 'UserSettings',
            },
        ),
    ]
