# Generated by Django 5.0.4 on 2024-05-14 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_usersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ArithmeticAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bohrium_access_token', models.CharField(blank=True, max_length=100, null=True)),
                ('bohrium_username', models.CharField(blank=True, max_length=50, null=True)),
                ('bohrium_password', models.CharField(blank=True, max_length=50, null=True)),
                ('bohrium_default_project', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arithmetic_access', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
