# Generated by Django 5.0.4 on 2024-06-11 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_userresource_arithmeticaccess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arithmeticaccess',
            name='bohrium_password',
        ),
        migrations.RemoveField(
            model_name='arithmeticaccess',
            name='bohrium_username',
        ),
        migrations.AddField(
            model_name='user',
            name='bohrium_account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, null=True, unique=True),
        ),
    ]
