# Generated by Django 5.0.4 on 2024-06-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_arithmeticaccess_bohrium_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bohrium_account',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
