# Generated by Django 5.0.4 on 2024-08-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_apitokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="arithmeticaccess",
            name="bohrium_username",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
