# Generated by Django 5.1.2 on 2024-11-06 09:57

import django.core.validators
import django.db.models.deletion
import flociety.models
import flociety.validates
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeDataBodyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Key 只能包含字母，数字和横杠，不允许空格和下划线，优先推荐小写字母与横杠', max_length=100, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, numbers, and hyphens. underscores is not allowed.', regex='^[a-zA-Z0-9-]+$')])),
                ('type', models.CharField(choices=[('DEFAULT', 'Default'), ('FILE', 'File'), ('TEXTAREA', 'Textarea'), ('SELECT', 'Select')], default='Default', help_text='Default 使用 jsonSchema 控制用户输入内容，Textarea 使用纯文本框控制用户输入内容，File 为让用户上传文件, Select 为选择框', max_length=50)),
                ('title', models.CharField(blank=True, help_text='建议填写，控制输入框的 placeholder', max_length=100, null=True)),
                ('source', models.JSONField(blank=True, help_text='source 为 body 的实际数据', null=True)),
                ('select_choices', models.JSONField(blank=True, help_text='select_choices 为选择框的选项，为对象列表，包含 name，value 两个字段', null=True)),
                ('attachment', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NodeDataTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField()),
                ('footer', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplateLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover', models.FileField(blank=True, default='workflow/default_cover.png', null=True, upload_to=flociety.models.workflow_cover_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NodeBodySchemaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_type', models.CharField(default='default', max_length=100)),
                ('schema', models.JSONField()),
                ('uiSchema', models.JSONField(blank=True, null=True)),
                ('body', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schema', to='flociety.nodedatabodytemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NodeDataHandleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Key 只能包含字母，数字和横杠，不允许空格和下划线', max_length=100, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, numbers, and hyphens. underscores is not allowed.', regex='^[a-zA-Z0-9-]+$')])),
                ('type', models.CharField(choices=[('target', 'Target'), ('source', 'Source')], max_length=10)),
                ('label', models.CharField(blank=True, help_text='Label 控制显示的文本，若为空则显示 key 的大写值', max_length=100, null=True)),
                ('data_source', models.CharField(blank=True, choices=[('handle', 'Handle'), ('body', 'Body'), ('compile', 'Compile')], max_length=10, null=True)),
                ('data_key', models.CharField(blank=True, max_length=100, null=True)),
                ('rope', models.CharField(blank=True, help_text='rope 即将失去作用，无需填写', max_length=100, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handles', to='flociety.nodedatatemplate')),
            ],
        ),
        migrations.CreateModel(
            name='NodeDataCompileTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Key 只能包含字母，数字和横杠，不允许空格和下划线', max_length=100, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, numbers, and hyphens. underscores is not allowed.', regex='^[a-zA-Z0-9-]+$')])),
                ('type', models.CharField(choices=[('Parameter', 'Parameter'), ('Artifact', 'Artifact')], default='Parameter', help_text='Parameter 为参数，Artifact 为输出文件路径', max_length=50)),
                ('script', models.TextField(blank=True, max_length=100, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('readable', models.BooleanField(default=False)),
                ('bodies', models.ManyToManyField(blank=True, related_name='compile', to='flociety.nodedatabodytemplate')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compile', to='flociety.nodedatatemplate')),
            ],
        ),
        migrations.AddField(
            model_name='nodedatabodytemplate',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body', to='flociety.nodedatatemplate'),
        ),
        migrations.CreateModel(
            name='NodeTemplateLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, numbers, underscores, and hyphens.', regex='^[a-zA-Z0-9_-]+$'), flociety.validates.validate_node_name])),
                ('description', models.TextField(blank=True, null=True)),
                ('version', models.CharField(default='0.0.0', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('Step', 'Step'), ('ILab', 'ILab'), ('Solver', 'Solver'), ('Basic', 'Basic'), ('Select', 'Select'), ('Input', 'Input')], max_length=50)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='node_template_library', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='nodedatatemplate',
            name='node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='node_data', to='flociety.nodetemplatelibrary'),
        ),
    ]
