# Generated by Django 5.0.4 on 2024-08-18 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flociety", "0002_alter_nodedatatemplate_node"),
    ]

    operations = [
        migrations.CreateModel(
            name="NodeBodySchemaTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("panel_type", models.CharField(default="default", max_length=100)),
                ("schema", models.JSONField()),
                ("uiSchema", models.JSONField()),
                (
                    "body",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schema",
                        to="flociety.nodedatabodytemplate",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
