# Generated by Django 5.0.4 on 2024-08-19 06:32

import django.core.validators
import flociety.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flociety", "0003_nodebodyschematemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nodedatacompiletemplate",
            name="script",
            field=models.CharField(default="default", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="nodedatacompiletemplate",
            name="type",
            field=models.CharField(default="file", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="nodedatatemplate",
            name="header",
            field=models.TextField(default="default"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="nodetemplatelibrary",
            name="name",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Name can only contain letters, numbers, underscores, and hyphens.",
                        regex="^[a-zA-Z0-9_-]+$",
                    ),
                    flociety.models.validate_node_name,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="nodetemplatelibrary",
            name="type",
            field=models.CharField(
                choices=[
                    ("Sequential", "Sequential"),
                    ("Solver", "Solver"),
                    ("Basic", "Basic"),
                    ("Select", "Select"),
                    ("Input", "Input"),
                ],
                max_length=50,
            ),
        ),
    ]
