# Generated by Django 5.0.4 on 2024-08-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flociety", "0004_alter_nodedatacompiletemplate_script_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nodebodyschematemplate",
            name="uiSchema",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
