# Generated by Django 5.0.4 on 2024-08-23 02:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flociety", "0005_alter_nodebodyschematemplate_uischema"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nodedatahandletemplate",
            name="key",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Name can only contain letters, numbers, and hyphens. underscores is not allowed.",
                        regex="^[a-zA-Z0-9-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="nodetemplatelibrary",
            name="type",
            field=models.CharField(
                choices=[
                    ("Step", "Step"),
                    ("ILab", "ILab"),
                    ("Solver", "Solver"),
                    ("Basic", "Basic"),
                    ("Select", "Select"),
                    ("Input", "Input"),
                ],
                max_length=50,
            ),
        ),
    ]
