# Generated by Django 5.1.1 on 2024-09-20 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flociety', '0007_alter_nodetemplatelibrary_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodetemplateversion',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nodedatatemplate',
            name='node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='node_data', to='flociety.nodetemplateversion'),
        ),
    ]
