# Generated by Django 5.1.1 on 2024-09-20 11:01

import django.core.validators
import django.db.models.deletion
import flociety.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flociety', '0008_nodetemplateversion_info_alter_nodedatatemplate_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodedatatemplate',
            name='node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='node_data', to='flociety.nodetemplatelibrary'),
        ),
        migrations.AlterUniqueTogether(
            name='nodetemplatelibrary',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='nodetemplatelibrary',
            name='version',
            field=models.CharField(default='0.0.0', max_length=50),
        ),
        migrations.AlterField(
            model_name='nodetemplatelibrary',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, numbers, underscores, and hyphens.', regex='^[a-zA-Z0-9_-]+$'), flociety.models.validate_node_name]),
        ),
        migrations.AlterUniqueTogether(
            name='nodetemplatelibrary',
            unique_together={('name', 'version')},
        ),
        migrations.DeleteModel(
            name='NodeTemplateVersion',
        ),
    ]
