# Generated by Django 5.1.1 on 2024-09-23 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flociety', '0010_workflowtemplate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkflowTemplate',
        ),
    ]
