# Generated by Django 5.1.1 on 2024-09-24 07:15

import django.db.models.deletion
import flociety.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flociety', '0011_delete_workflowtemplate'),
        ('workflow', '0031_remove_workflow_cover_remove_workflow_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTemplateLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('cover', models.FileField(blank=True, null=True, upload_to=flociety.models.workflow_cover_path)),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='workflow.workflow')),
            ],
        ),
    ]
