# Generated by Django 5.1.1 on 2024-09-24 07:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flociety', '0012_workflowtemplatelibrary'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtemplatelibrary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workflowtemplatelibrary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
