# Generated by Django 5.1.1 on 2024-10-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flociety', '0015_alter_nodedatabodytemplate_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodedatabodytemplate',
            name='select_choices',
            field=models.JSONField(blank=True, help_text='select_choices 为选择框的选项，为对象列表', null=True),
        ),
        migrations.AlterField(
            model_name='nodedatabodytemplate',
            name='source',
            field=models.JSONField(blank=True, help_text='source 为 body 的实际数据', null=True),
        ),
        migrations.AlterField(
            model_name='nodedatabodytemplate',
            name='title',
            field=models.CharField(blank=True, help_text='建议填写，控制输入框的 placeholder', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nodedatabodytemplate',
            name='type',
            field=models.CharField(choices=[('Default', 'Default'), ('File', 'File'), ('Textarea', 'Textarea'), ('Select', 'Select')], default='Default', help_text='Default 使用 jsonSchema 控制用户输入内容，Textarea 使用纯文本框控制用户输入内容，File 为让用户上传文件, Select 为选择框', max_length=50),
        ),
    ]
