# Generated by Django 5.1.2 on 2024-10-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flociety', '0018_alter_nodedatabodytemplate_select_choices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodedatacompiletemplate',
            name='type',
            field=models.CharField(choices=[('Parameter', 'Parameter'), ('Artifact', 'Artifact')], max_length=50),
        ),
    ]
