# Generated by Django 5.1.2 on 2024-10-31 09:45

import flociety.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flociety', '0020_alter_nodedatacompiletemplate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowtemplatelibrary',
            name='cover',
            field=models.FileField(blank=True, default='workflow/default_cover.png', null=True, upload_to=flociety.models.workflow_cover_path),
        ),
    ]
