# Generated by Django 5.1.2 on 2024-10-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flociety', '0021_alter_workflowtemplatelibrary_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodedatacompiletemplate',
            name='script',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nodedatacompiletemplate',
            name='source',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nodedatahandletemplate',
            name='label',
            field=models.CharField(blank=True, help_text='Label 控制显示的文本，若为空则显示 key 的大写值', max_length=100, null=True),
        ),
    ]
