# Generated by Django 5.1.2 on 2024-10-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flociety', '0022_alter_nodedatacompiletemplate_script_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodedatacompiletemplate',
            name='source',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
