# Generated by Django 5.1.2 on 2024-10-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flociety', '0023_alter_nodedatacompiletemplate_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodedatacompiletemplate',
            name='script',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nodedatacompiletemplate',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
    ]
