services:
  db:
    image: postgres:16.4-bullseye
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '48195:5432'

  elasticsearch:
    image: elasticsearch:8.15.0
    environment:
      - discovery.type=single-node
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - xpack.security.http.ssl.enabled=false
      - xpack.license.self_generated.type=trial
    ports:
      - '48196:9200'
    # Limiting the resources for the elasticsearch container
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '2G'
        reservations:
          cpus: '1.0'
          memory: '1G'

  backend:
    restart: unless-stopped
    image: registry.cn-beijing.aliyuncs.com/protium/backend:latest
    env_file:
      - .env
    environment:
      - ENV=production
    command: ['/app/entrypoint.sh']
    ports:
      - '48197:8000'
    depends_on:
      - elasticsearch
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Add host permission in container

  frontend:
    restart: unless-stopped
    image: registry.cn-beijing.aliyuncs.com/protium/frontend:latest
    env_file:
      - .env
    ports:
      - '32233:3000'
    depends_on:
      - backend

  workflow:
    restart: unless-stopped
    image: registry.cn-beijing.aliyuncs.com/protium/workflow:latest
    env_file:
      - .env
    ports:
      - '32234:3003'
    depends_on:
      - frontend

  docfront:
    restart: unless-stopped
    image: registry.cn-beijing.aliyuncs.com/protium/docfront:latest
    env_file:
      - .env
    ports:
      - '32235:4000'
    depends_on:
      - frontend

volumes:
  pgdata:
