services:
  db:
    restart: unless-stopped
    image: postgres:16.4-bullseye
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  elasticsearch:
    restart: unless-stopped
    image: elasticsearch:8.15.0
    environment:
      - discovery.type=single-node
      - ELASTIC_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - xpack.security.http.ssl.enabled=false
      - xpack.license.self_generated.type=trial
      - logger.level=DEBUG
    ports:
      - '9200:9200'
    # Limiting the resources for the elasticsearch container
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '2G'
        reservations:
          cpus: '1.0'
          memory: '1G'

  backend:
    restart: unless-stopped
    build:
      context: ./Backend
    image: ghcr.io/mile-away/protium/backend:latest
    env_file:
      - .env
    environment:
      - ENV=development
    volumes:
      - ./Backend:/app
    command: ['/app/entrypoint.sh']
    ports:
      - '8000:8000'
    depends_on:
      - elasticsearch
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Add host permission in container

  frontend:
    restart: unless-stopped
    build:
      context: ./Frontend
    image: ghcr.io/mile-away/protium/frontend:latest
    command: ['yarn', 'dev']
    env_file:
      - .env
    volumes:
      - ./Frontend:/app
    ports:
      - '3000:3000'
    depends_on:
      - backend

  workflow:
    restart: unless-stopped
    build:
      context: ./Protium
    image: ghcr.io/mile-away/protium/workflow:latest
    # command: sh -c "yarn dev && tail -f /dev/null"
    command: ['yarn', 'dev']
    env_file:
      - .env
    volumes:
      - ./Protium:/app
    ports:
      - '3003:3003'
    depends_on:
      - frontend

  docfront:
    restart: unless-stopped
    build:
      context: ./DocFront
    image: ghcr.io/mile-away/protium/docfront:latest
    command: ['yarn', 'dev']
    env_file:
      - .env
    volumes:
      - ./DocFront:/app
    ports:
      - '4000:4000'
    depends_on:
      - frontend

volumes:
  pgdata:
