# Generated by Django 4.2.9 on 2024-04-03 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0016_remove_uuid_null"),
        ("server", "0015_remove_channel_admin_channel_admins_and_more"),
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsearchhistory",
            name="channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="server.channel",
            ),
        ),
        migrations.AddField(
            model_name="globalsearchhistory",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="document.document",
            ),
        ),
        migrations.AddField(
            model_name="globalsearchhistory",
            name="source",
            field=models.CharField(
                choices=[("global", "Global"), ("channel", "Channel")],
                default="global",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="globalsearchhistory",
            name="type",
            field=models.CharField(
                choices=[("document", "Document"), ("channel", "Channel")],
                max_length=20,
            ),
        ),
    ]
