services:
  db:
    restart: unless-stopped
    image: postgres:16.4-bullseye
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "48195:5432"

  elasticsearch:
    restart: unless-stopped
    image: elasticsearch:8.15.0
    environment:
      - discovery.type=single-node
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - xpack.security.http.ssl.enabled=false
      - xpack.license.self_generated.type=trial
    ports:
      - "48196:9200"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "2G"
        reservations:
          cpus: "1.0"
          memory: "512M"

  backend:
    restart: unless-stopped
    image: mileaway/protium-backend:latest
    env_file:
      - .env
    environment:
      - ENV=production
    command: ["/app/entrypoint.sh"]
    ports:
      - "48197:8000"
    depends_on:
      - elasticsearch
      - db

  frontend:
    restart: unless-stopped
    image: mileaway/protium-frontend:latest
    ports:
      - "32233:3000"
    depends_on:
      - backend

  workflow:
    restart: unless-stopped
    image: mileaway/protium-workflow:latest
    ports:
      - "32234:3003"
    depends_on:
      - frontend

  docfront:
    restart: unless-stopped
    image: mileaway/protium-docfront:latest
    ports:
      - "32235:4000"
    depends_on:
      - frontend

volumes:
  pgdata: