# Generated by Django 5.0.4 on 2024-05-23 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0018_alter_server_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubServerIntergration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github', to='server.server')),
            ],
        ),
        migrations.CreateModel(
            name='GithubUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=255)),
                ('node_id', models.CharField(max_length=255)),
                ('avatar_url', models.URLField()),
                ('gravatar_id', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField()),
                ('html_url', models.URLField()),
                ('followers_url', models.URLField()),
                ('following_url', models.URLField()),
                ('gists_url', models.URLField()),
                ('starred_url', models.URLField()),
                ('subscriptions_url', models.URLField()),
                ('organizations_url', models.URLField()),
                ('repos_url', models.URLField()),
                ('events_url', models.URLField()),
                ('received_events_url', models.URLField()),
                ('type', models.CharField(max_length=255)),
                ('site_admin', models.BooleanField()),
                ('server', models.ManyToManyField(related_name='users', to='integration.githubserverintergration')),
            ],
        ),
        migrations.CreateModel(
            name='GithubRelease',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('assets_url', models.URLField()),
                ('upload_url', models.URLField()),
                ('html_url', models.URLField()),
                ('node_id', models.CharField(max_length=255)),
                ('tag_name', models.CharField(max_length=255)),
                ('target_commitish', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('draft', models.BooleanField()),
                ('prerelease', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('published_at', models.DateTimeField()),
                ('tarball_url', models.URLField()),
                ('zipball_url', models.URLField()),
                ('body', models.TextField()),
                ('reactions', models.JSONField()),
                ('mentions_count', models.IntegerField()),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='integration.githubserverintergration')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='integration.githubuser')),
            ],
        ),
        migrations.CreateModel(
            name='GithubAsset',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('node_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, max_length=25, null=True)),
                ('content_type', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('download_count', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('browser_download_url', models.URLField()),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='integration.githubrelease')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration.githubuser')),
            ],
        ),
    ]
