# Generated by Django 5.1.2 on 2024-11-06 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GithubRelease',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('assets_url', models.URLField(blank=True, null=True)),
                ('upload_url', models.URLField(blank=True, null=True)),
                ('html_url', models.URLField(blank=True, null=True)),
                ('node_id', models.CharField(blank=True, max_length=255, null=True)),
                ('tag_name', models.CharField(blank=True, max_length=255, null=True)),
                ('target_commitish', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('draft', models.BooleanField(blank=True, null=True)),
                ('prerelease', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('published_at', models.DateTimeField()),
                ('tarball_url', models.URLField(blank=True, null=True)),
                ('zipball_url', models.URLField(blank=True, null=True)),
                ('body', models.TextField()),
                ('reactions', models.JSONField(blank=True, null=True)),
                ('mentions_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GithubServerIntergration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GithubUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=255)),
                ('node_id', models.CharField(max_length=255)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('gravatar_id', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('html_url', models.URLField(blank=True, null=True)),
                ('followers_url', models.URLField(blank=True, null=True)),
                ('following_url', models.URLField(blank=True, null=True)),
                ('gists_url', models.URLField(blank=True, null=True)),
                ('starred_url', models.URLField(blank=True, null=True)),
                ('subscriptions_url', models.URLField(blank=True, null=True)),
                ('organizations_url', models.URLField(blank=True, null=True)),
                ('repos_url', models.URLField(blank=True, null=True)),
                ('events_url', models.URLField(blank=True, null=True)),
                ('received_events_url', models.URLField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('site_admin', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GithubAsset',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('node_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.IntegerField()),
                ('download_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('browser_download_url', models.URLField(blank=True, null=True)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='integration.githubrelease')),
            ],
        ),
    ]
