# Generated by Django 5.1.2 on 2024-11-06 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integration', '0001_initial'),
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubserverintergration',
            name='server',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github', to='server.server'),
        ),
        migrations.AddField(
            model_name='githubrelease',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='integration.githubserverintergration'),
        ),
        migrations.AddField(
            model_name='githubrelease',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='integration.githubuser'),
        ),
        migrations.AddField(
            model_name='githubasset',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration.githubuser'),
        ),
    ]
