# Generated by Django 5.0.4 on 2024-05-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0003_alter_githubasset_browser_download_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubasset',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
