# Generated by Django 4.2.9 on 2024-02-26 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("document", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="cooperators",
            field=models.ManyToManyField(
                blank=True, related_name="cooperators", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
