# Generated by Django 4.2.9 on 2024-03-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0004_rename_tags_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
