# Generated by Django 4.2.9 on 2024-03-06 09:05

from django.db import migrations, models
import django.db.models.deletion
import document.models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0005_alter_document_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="public",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to=document.models.document_image_path),
                ),
                ("size", models.BigIntegerField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="document.document",
                    ),
                ),
            ],
        ),
    ]
