# Generated by Django 4.2.9 on 2024-03-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0006_document_public_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="title",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
