# Generated by Django 4.2.9 on 2024-03-08 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0007_alter_document_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="document",
            old_name="public",
            new_name="publish",
        ),
    ]
