# Generated by Django 4.2.9 on 2024-03-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0008_rename_public_document_publish"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="agree",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="disagree",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
