# Generated by Django 4.2.9 on 2024-03-26 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("document", "0009_document_agree_document_disagree"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_author",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
