# Generated by Django 4.2.9 on 2024-03-28 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0010_alter_document_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="agree",
        ),
        migrations.RemoveField(
            model_name="document",
            name="disagree",
        ),
        migrations.CreateModel(
            name="DocumentActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("view", models.PositiveIntegerField(default=0)),
                ("agree", models.PositiveIntegerField(default=0)),
                ("disagree", models.PositiveIntegerField(default=0)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="document.document",
                    ),
                ),
            ],
        ),
    ]
