# Generated by Django 4.2.9 on 2024-03-28 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0012_documentactivityuser"),
    ]

    operations = [
        migrations.RenameField(
            model_name="documentactivityuser",
            old_name="action",
            new_name="vote",
        ),
    ]
