# Generated by Django 4.2.9 on 2024-03-29 06:56

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0015_populate_uuid_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False,),
        ),
    ]
