# Generated by Django 5.1.2 on 2024-11-06 09:57

import server.models
import server.validator
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.FileField(blank=True, null=True, upload_to=server.models.category_icon_path, validators=[server.validator.validate_icon_image_size, server.validator.validate_image_file_extension])),
            ],
        ),
        migrations.CreateModel(
            name='PinnedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('chinese_description', models.CharField(blank=True, max_length=500, null=True)),
                ('icon', models.ImageField(blank=True, help_text='展示在列表中的 Logo 图片', null=True, upload_to=server.models.server_icon_path, validators=[server.validator.validate_icon_image_size, server.validator.validate_image_file_extension])),
                ('banner', models.ImageField(blank=True, help_text='创建服务器时，展示在首页的图片', null=True, upload_to=server.models.server_banner_path)),
                ('github_url', models.URLField(blank=True, help_text='Space 对应的 Github 地址', null=True)),
                ('document_url', models.URLField(blank=True, help_text='Space 对应的 Doc 文件夹的地址', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enable_releases', models.BooleanField(default=False, help_text='是否展示 Github Release')),
                ('enable_discussion', models.BooleanField(default=False, help_text='是否开启讨论区')),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('icon', models.FileField(blank=True, null=True, upload_to=server.models.channel_icon_path, validators=[server.validator.validate_image_file_extension, server.validator.validate_icon_image_size])),
                ('privacy', models.CharField(choices=[('public', 'Public'), ('apply', 'Apply'), ('memberOnly', 'MemberOnly'), ('private', 'Private')], default='public', max_length=20)),
                ('progress', models.CharField(choices=[('archived', 'Archived'), ('inProgress', 'InProgress'), ('completed', 'Completed')], default='inProgress', max_length=20)),
                ('admins', models.ManyToManyField(blank=True, related_name='channel_admins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
