# Generated by Django 5.1.2 on 2024-11-06 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('document', '0001_initial'),
        ('server', '0001_initial'),
        ('webchat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='latest_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_latest_message', to='webchat.message'),
        ),
        migrations.AddField(
            model_name='channel',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='channel_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pinneddocument',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.document'),
        ),
        migrations.AddField(
            model_name='server',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='server_admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='server',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='server_category', to='server.category'),
        ),
        migrations.AddField(
            model_name='server',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='server_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='server',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='server_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='server',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='server',
            name='pinned_manuscript',
            field=models.ManyToManyField(blank=True, help_text='管理员在创建 Space 时 Pin 在首页的文档', through='server.PinnedDocument', to='document.document'),
        ),
        migrations.AddField(
            model_name='server',
            name='readme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='server_readme', to='document.document'),
        ),
        migrations.AddField(
            model_name='pinneddocument',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.server'),
        ),
        migrations.AddField(
            model_name='channel',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_server', to='server.server'),
        ),
        migrations.AlterUniqueTogether(
            name='pinneddocument',
            unique_together={('document', 'server')},
        ),
    ]
