# Generated by Django 4.2.9 on 2024-03-19 11:09

from django.db import migrations, models
import django.db.models.deletion
import server.models
import server.validator


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0009_document_agree_document_disagree"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="bannar_image",
            field=models.ImageField(
                blank=True,
                help_text="创建服务器时，展示在首页的图片",
                null=True,
                upload_to=server.models.server_banner_path,
            ),
        ),
        migrations.AddField(
            model_name="server",
            name="document_url",
            field=models.URLField(
                blank=True, help_text="Space 对应的 Doc 文件夹的地址", null=True
            ),
        ),
        migrations.AddField(
            model_name="server",
            name="github_url",
            field=models.URLField(
                blank=True, help_text="Space 对应的 Github 地址", null=True
            ),
        ),
        migrations.AddField(
            model_name="server",
            name="groups",
            field=models.ManyToManyField(related_name="server_groups", to="auth.group"),
        ),
        migrations.AddField(
            model_name="server",
            name="icon",
            field=models.ImageField(
                blank=True,
                help_text="展示在列表中的 Logo 图片",
                null=True,
                upload_to=server.models.server_icon_path,
                validators=[
                    server.validator.validate_icon_image_size,
                    server.validator.validate_image_file_extension,
                ],
            ),
        ),
        migrations.AddField(
            model_name="server",
            name="pinned_manuscript",
            field=models.ManyToManyField(
                help_text="管理员在创建 Space 时 pin 在首页的文档",
                related_name="server_document",
                to="document.document",
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="server_category",
                to="server.category",
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
