# Generated by Django 4.2.9 on 2024-03-19 13:33

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("document", "0009_document_agree_document_disagree"),
        ("server", "0002_server_bannar_image_server_document_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="chinese_description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="server",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="server",
            name="groups",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="server_groups", to="auth.group"
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="server_members",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="pinned_manuscript",
            field=models.ManyToManyField(
                blank=True,
                help_text="管理员在创建 Space 时 pin 在首页的文档",
                null=True,
                to="document.document",
            ),
        ),
    ]
