# Generated by Django 4.2.9 on 2024-03-20 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0003_server_chinese_description_server_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="server",
            old_name="bannar_image",
            new_name="banner",
        ),
    ]
