# Generated by Django 4.2.9 on 2024-03-21 07:17

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("server", "0004_rename_bannar_image_server_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="channel",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="channel_members",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="progress",
            field=models.CharField(
                choices=[
                    ("archived", "Archived"),
                    ("inProgress", "InProgress"),
                    ("finished", "Finished"),
                ],
                default="inProgress",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="status",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private")],
                default="public",
                max_length=20,
            ),
        ),
    ]
