# Generated by Django 4.2.9 on 2024-03-23 08:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0009_document_agree_document_disagree"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("server", "0005_channel_created_at_channel_members_channel_progress_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="channel_members", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="server_groups", to="auth.group"
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="server_members", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="pinned_manuscript",
            field=models.ManyToManyField(
                blank=True,
                help_text="管理员在创建 Space 时 pin 在首页的文档",
                to="document.document",
            ),
        ),
    ]
