# Generated by Django 4.2.9 on 2024-03-29 09:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0006_alter_channel_members_alter_server_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
