# Generated by Django 4.2.9 on 2024-03-29 09:09

import uuid

from django.db import migrations


def gen_server_uuid(apps, schema_editor):
    MyModel = apps.get_model("server", "Server")
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


def gen_channel_uuid(apps, schema_editor):
    MyModel = apps.get_model("server", "Channel")
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0007_server_uuid"),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_server_uuid, reverse_code=migrations.RunPython.noop),

    ]
