# Generated by Django 4.2.9 on 2024-03-29 09:23


import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0008_auto_20240329_1722"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                unique=True,
                editable=False,
            ),
        )
    ]
