# Generated by Django 4.2.9 on 2024-03-29 09:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0009_auto_20240329_1723"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
