# Generated by Django 4.2.9 on 2024-03-30 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("webchat", "0001_initial"),
        ("server", "0012_auto_20240329_1724"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="latest_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="channel_latest_message",
                to="webchat.message",
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="status",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("protected", "Protected"),
                    ("memberOnly", "MemberOnly"),
                    ("private", "Private"),
                ],
                default="public",
                max_length=20,
            ),
        ),
    ]
