# Generated by Django 4.2.9 on 2024-03-31 06:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("server", "0013_channel_latest_message_alter_channel_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="channel",
            old_name="status",
            new_name="privacy",
        ),
        migrations.AddField(
            model_name="channel",
            name="admin",
            field=models.ManyToManyField(
                blank=True, related_name="channel_admin", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
