# Generated by Django 4.2.9 on 2024-03-31 07:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("server", "0014_rename_status_channel_privacy_channel_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="channel",
            name="admin",
        ),
        migrations.AddField(
            model_name="channel",
            name="admins",
            field=models.ManyToManyField(
                blank=True, related_name="channel_admins", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="privacy",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("apply", "Apply"),
                    ("memberOnly", "MemberOnly"),
                    ("private", "Private"),
                ],
                default="public",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="progress",
            field=models.CharField(
                choices=[
                    ("archived", "Archived"),
                    ("inProgress", "InProgress"),
                    ("completed", "Completed"),
                ],
                default="inProgress",
                max_length=20,
            ),
        ),
    ]
