# Generated by Django 4.2.9 on 2024-04-12 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0016_remove_uuid_null"),
        ("server", "0015_remove_channel_admin_channel_admins_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="readme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="server_readme",
                to="document.document",
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="server",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
