# Generated by Django 4.2.9 on 2024-04-12 11:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("server", "0016_server_readme_alter_channel_name_alter_server_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="admins",
            field=models.ManyToManyField(
                blank=True, related_name="server_admins", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
