# Generated by Django 5.0.4 on 2024-04-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0017_server_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
