# Generated by Django 5.0.4 on 2024-05-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0018_alter_server_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='enable_discussion',
            field=models.BooleanField(default=False, help_text='是否开启讨论区'),
        ),
        migrations.AddField(
            model_name='server',
            name='enable_releases',
            field=models.BooleanField(default=False, help_text='是否展示 Github Release'),
        ),
    ]
