# Generated by Django 5.0.4 on 2024-05-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0019_server_enable_discussion_server_enable_releases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='category',
        ),
        migrations.AddField(
            model_name='server',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='server_category', to='server.category'),
        ),
    ]
