# Generated by Django 5.0.4 on 2024-05-27 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0016_remove_uuid_null'),
        ('server', '0020_remove_server_category_server_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='pinned_manuscript',
        ),
        migrations.CreateModel(
            name='PinnedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.document')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.server')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('document', 'server')},
            },
        ),
    ]
