# Generated by Django 5.0.4 on 2024-05-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0016_remove_uuid_null'),
        ('server', '0021_remove_server_pinned_manuscript_pinneddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='pinned_manuscript',
            field=models.ManyToManyField(blank=True, help_text='管理员在创建 Space 时 pin 在首页的文档', through='server.PinnedDocument', to='document.document'),
        ),
    ]
