# Generated by Django 5.1.2 on 2024-11-06 10:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialNode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('repository', 'Repository'), ('plate', 'Plate'), ('instance', 'Instance')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CalculationEnv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('argo_api', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_envs', to='environment.environment')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentEnv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiment_envs', to='environment.environment')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialInstance',
            fields=[
                ('material_node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='environment.materialnode')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialPlate',
            fields=[
                ('material_node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='environment.materialnode')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialRepository',
            fields=[
                ('material_node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='environment.materialnode')),
                ('position', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='materialnode',
            name='experiment_env',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environment.experimentenv'),
        ),
        migrations.AddField(
            model_name='materialnode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='environment.materialnode'),
        ),
        migrations.AlterUniqueTogether(
            name='materialnode',
            unique_together={('name', 'parent', 'experiment_env')},
        ),
    ]
