# Generated by Django 4.2.9 on 2024-03-30 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0013_channel_latest_message_alter_channel_status"),
        ("webchat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="channel_id",
        ),
        migrations.AddField(
            model_name="conversation",
            name="channel",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversation",
                to="server.channel",
            ),
            preserve_default=False,
        ),
    ]
