# Generated by Django 5.1.2 on 2024-11-06 09:57

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flociety', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('running', 'Running'), ('finished', 'Finished'), ('canceled', 'Canceled'), ('failed', 'Failed')], default='draft', max_length=50)),
                ('public', models.BooleanField(default=False)),
                ('as_template', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowConsole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consoles', to='workflow.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('position', models.JSONField(default=dict)),
                ('positionAbsolute', models.JSONField(default=dict)),
                ('width', models.IntegerField(default=200)),
                ('height', models.IntegerField(default=250)),
                ('dragHandle', models.CharField(blank=True, default='.drag-handle', max_length=50, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('skipped', 'Skipped'), ('success', 'Success'), ('failed', 'Failed'), ('running', 'Running'), ('pending', 'Pending')], default='draft', max_length=10)),
                ('minimized', models.BooleanField(default=False)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flociety.nodetemplatelibrary')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='workflow.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowNodeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField()),
                ('footer', models.TextField(blank=True, null=True)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='node_data', to='workflow.workflownode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowNodeBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Key 只能包含字母，数字和横杠，不允许空格和下划线，优先推荐小写字母与横杠', max_length=100, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, numbers, and hyphens. underscores is not allowed.', regex='^[a-zA-Z0-9-]+$')])),
                ('type', models.CharField(choices=[('DEFAULT', 'Default'), ('FILE', 'File'), ('TEXTAREA', 'Textarea'), ('SELECT', 'Select')], default='Default', help_text='Default 使用 jsonSchema 控制用户输入内容，Textarea 使用纯文本框控制用户输入内容，File 为让用户上传文件, Select 为选择框', max_length=50)),
                ('title', models.CharField(blank=True, help_text='建议填写，控制输入框的 placeholder', max_length=100, null=True)),
                ('source', models.JSONField(blank=True, help_text='source 为 body 的实际数据', null=True)),
                ('select_choices', models.JSONField(blank=True, help_text='select_choices 为选择框的选项，为对象列表，包含 name，value 两个字段', null=True)),
                ('attachment', models.CharField(blank=True, max_length=100, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body', to='workflow.workflownodedata')),
            ],
            options={
                'unique_together': {('node', 'key')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowNodeHandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Key 只能包含字母，数字和横杠，不允许空格和下划线', max_length=100, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, numbers, and hyphens. underscores is not allowed.', regex='^[a-zA-Z0-9-]+$')])),
                ('type', models.CharField(choices=[('target', 'Target'), ('source', 'Source')], max_length=10)),
                ('label', models.CharField(blank=True, help_text='Label 控制显示的文本，若为空则显示 key 的大写值', max_length=100, null=True)),
                ('data_source', models.CharField(blank=True, choices=[('handle', 'Handle'), ('body', 'Body'), ('compile', 'Compile')], max_length=10, null=True)),
                ('data_key', models.CharField(blank=True, max_length=100, null=True)),
                ('rope', models.CharField(blank=True, help_text='rope 即将失去作用，无需填写', max_length=100, null=True)),
                ('hasConnected', models.BooleanField(default=False)),
                ('required', models.BooleanField(default=False)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handles', to='workflow.workflownodedata')),
            ],
            options={
                'unique_together': {('node', 'type', 'key')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_id', models.CharField(max_length=250, unique=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='workflow.workflow')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_source', to='workflow.workflownode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_target', to='workflow.workflownode')),
                ('sourceHandle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_sourceHandle', to='workflow.workflownodehandle')),
                ('targetHandle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_targetHandle', to='workflow.workflownodehandle')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowNodeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='workflow.workflownodedata')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('platform', models.CharField(max_length=50)),
                ('task_id', models.CharField(max_length=100)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('output', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workflow.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowNodeCompile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Key 只能包含字母，数字和横杠，不允许空格和下划线', max_length=100, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, numbers, and hyphens. underscores is not allowed.', regex='^[a-zA-Z0-9-]+$')])),
                ('type', models.CharField(choices=[('Parameter', 'Parameter'), ('Artifact', 'Artifact')], default='Parameter', help_text='Parameter 为参数，Artifact 为输出文件路径', max_length=50)),
                ('script', models.TextField(blank=True, max_length=100, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('readable', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('bodies', models.ManyToManyField(blank=True, related_name='compile', to='workflow.workflownodebody')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compile', to='workflow.workflownodedata')),
            ],
            options={
                'unique_together': {('node', 'key')},
            },
        ),
    ]
