# Generated by Django 5.0.4 on 2024-04-29 04:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('position', models.JSONField(default=dict)),
                ('positionAbsolute', models.JSONField(default=dict)),
                ('width', models.IntegerField(default=200)),
                ('height', models.IntegerField(default=250)),
                ('dragHandle', models.CharField(blank=True, max_length=50, null=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='workflow.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='workflow.workflow')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_edges', to='workflow.workflownode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_edges', to='workflow.workflownode')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowNodeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
                ('footer', models.TextField(blank=True, null=True)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='workflow.workflownode')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowNodeBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('source', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('attachment', models.CharField(blank=True, max_length=100, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body', to='workflow.workflownodedata')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowNodeHandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('target', 'Target'), ('source', 'Source')], max_length=10)),
                ('has_connected', models.BooleanField(default=False)),
                ('required', models.BooleanField(default=False)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handles', to='workflow.workflownodedata')),
            ],
            options={
                'unique_together': {('node', 'type', 'key')},
            },
        ),
    ]
