# Generated by Django 5.0.4 on 2024-04-29 06:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workflowedge",
            name="uuid",
        ),
        migrations.AddField(
            model_name="workflowedge",
            name="connection_id",
            field=models.CharField(
                default="reactflow__edge-4f01dd78-5091-46a9-b5b8-4521b251493e4f01dd78-5091-46a9-b5b8-4521b251493e-source-poscar-74c8d787-0678-43c9-94ad-6350aa4706ad74c8d787-0678-43c9-94ad-6350aa4706ad-target-poscar",
                max_length=250,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workflowedge",
            name="sourceHandle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="edges_sourceHandle",
                to="workflow.workflownodehandle",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workflowedge",
            name="targetHandle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="edges_targetHandle",
                to="workflow.workflownodehandle",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="workflowedge",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="edges_source", to="workflow.workflownode"
            ),
        ),
        migrations.AlterField(
            model_name="workflowedge",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="edges_target", to="workflow.workflownode"
            ),
        ),
    ]
