# Generated by Django 5.0.4 on 2024-04-29 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_remove_workflowedge_uuid_workflowedge_connection_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflownodehandle',
            old_name='has_connected',
            new_name='hasConnected',
        ),
    ]
