# Generated by Django 5.0.4 on 2024-04-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_rename_has_connected_workflownodehandle_hasconnected'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='isRunning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflow',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflow',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('running', 'Running'), ('finished', 'Finished'), ('canceled', 'Canceled'), ('failed', 'Failed')], default='draft', max_length=50),
        ),
        migrations.AddField(
            model_name='workflownode',
            name='isRunning',
            field=models.BooleanField(default=False),
        ),
    ]
