# Generated by Django 5.0.4 on 2024-04-29 16:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_workflow_isrunning_workflow_public_workflow_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflownodebody',
            name='key',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='workflownodebody',
            unique_together={('node', 'key')},
        ),
        migrations.CreateModel(
            name='WorkflowResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('key', models.CharField(max_length=100)),
                ('source', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('attachment', models.CharField(blank=True, max_length=100, null=True)),
                ('script', models.TextField(blank=True, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='workflow.workflownodedata')),
            ],
            options={
                'unique_together': {('node', 'key')},
            },
        ),
    ]
