# Generated by Django 5.0.4 on 2024-04-29 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_workflownodebody_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='isRunning',
        ),
    ]
