# Generated by Django 5.0.4 on 2024-05-02 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_remove_workflow_isrunning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflownode',
            name='positionAbsolute',
            field=models.JSONField(default={'x': 0, 'y': 0}),
        ),
        migrations.AlterField(
            model_name='workflownodedata',
            name='node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='node_data', to='workflow.workflownode'),
        ),
    ]
