# Generated by Django 5.0.4 on 2024-05-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_alter_workflownode_positionabsolute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflownode',
            name='positionAbsolute',
            field=models.JSONField(default=dict),
        ),
    ]
