# Generated by Django 5.0.4 on 2024-05-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_workflownoderesult_workflowtask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflownode',
            name='status',
            field=models.CharField(blank=True, choices=[('success', 'Success'), ('failed', 'Failed'), ('running', 'Running'), ('pending', 'Pending')], max_length=10, null=True),
        ),
    ]
