# Generated by Django 5.0.4 on 2024-05-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0012_alter_workflownode_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflownodehandle',
            name='data_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workflownodehandle',
            name='data_source',
            field=models.CharField(blank=True, choices=[('handle', 'Handle'), ('body', 'Body'), ('result', 'Result')], max_length=10, null=True),
        ),
    ]
