# Generated by Django 5.0.4 on 2024-05-09 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0013_workflownodehandle_data_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflownoderesult',
            name='bodies',
            field=models.ManyToManyField(blank=True, null=True, related_name='results', to='workflow.workflownodebody'),
        ),
    ]
