# Generated by Django 5.0.4 on 2024-05-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0014_workflownoderesult_bodies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflownoderesult',
            name='bodies',
            field=models.ManyToManyField(blank=True, related_name='results', to='workflow.workflownodebody'),
        ),
    ]
