# Generated by Django 5.0.4 on 2024-05-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0015_alter_workflownoderesult_bodies'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflownodehandle',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workflownoderesult',
            name='script',
            field=models.CharField(blank=True, null=True),
        ),
    ]
