# Generated by Django 5.0.4 on 2024-05-10 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0016_workflownodehandle_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflownodehandle',
            old_name='name',
            new_name='label',
        ),
    ]
