# Generated by Django 5.0.4 on 2024-05-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0017_rename_name_workflownodehandle_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflownode',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('skipped', 'Skipped'), ('success', 'Success'), ('failed', 'Failed'), ('running', 'Running'), ('pending', 'Pending')], default='draft', max_length=10),
        ),
    ]
