# Generated by Django 5.0.4 on 2024-06-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0019_workflowconsole_workflownodemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflownodehandle',
            name='rope',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
