# Generated by Django 5.0.4 on 2024-07-23 14:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0020_workflownodehandle_rope'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowNodeCompile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('key', models.CharField(max_length=100)),
                ('script', models.CharField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('attachment', models.CharField(blank=True, max_length=100, null=True)),
                ('bodies', models.ManyToManyField(blank=True, related_name='compile', to='workflow.workflownodebody')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compile', to='workflow.workflownodedata')),
            ],
            options={
                'unique_together': {('node', 'key')},
            },
        ),
        migrations.DeleteModel(
            name='WorkflowNodeResult',
        ),
    ]
