# Generated by Django 5.0.4 on 2024-08-15 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flociety", "0001_initial"),
        ("workflow", "0022_alter_workflownodebody_source_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workflownode",
            name="type",
        ),
        migrations.AddField(
            model_name="workflownode",
            name="node",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="flociety.nodetemplatelibrary",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="workflownodedata",
            name="header",
            field=models.TextField(blank=True, null=True),
        ),
    ]
