# Generated by Django 5.0.4 on 2024-08-15 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0023_remove_workflownode_type_workflownode_node_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workflownode",
            old_name="node",
            new_name="template",
        ),
    ]
