# Generated by Django 5.0.4 on 2024-08-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0024_rename_node_workflownode_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflownodecompile",
            name="script",
            field=models.CharField(default="default", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="workflownodecompile",
            name="type",
            field=models.CharField(default="file", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="workflownodedata",
            name="header",
            field=models.TextField(default="default"),
            preserve_default=False,
        ),
    ]
