# Generated by Django 5.0.4 on 2024-08-23 02:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0025_alter_workflownodecompile_script_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflownodehandle",
            name="key",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Name can only contain letters, numbers, and hyphens. underscores is not allowed.",
                        regex="^[a-zA-Z0-9-]+$",
                    )
                ],
            ),
        ),
    ]
