# Generated by Django 5.1 on 2024-08-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0026_alter_workflownodehandle_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflownode',
            name='dragHandle',
            field=models.CharField(blank=True, default='.drag-handle', max_length=50, null=True),
        ),
    ]
