# Generated by Django 5.1.1 on 2024-09-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0028_alter_workflownodehandle_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='as_template',
            field=models.BooleanField(default=False),
        ),
    ]
