# Generated by Django 5.1.1 on 2024-09-23 09:32

import workflow.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0029_workflow_as_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to=workflow.models.workflow_cover_path),
        ),
    ]
