# Generated by Django 5.1.1 on 2024-09-24 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0030_workflow_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='description',
        ),
    ]
