# Generated by Django 5.1.1 on 2024-09-24 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0031_remove_workflow_cover_remove_workflow_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflownodebody',
            name='key',
            field=models.CharField(help_text='Key 只能包含字母，数字和横杠，不允许空格和下划线', max_length=100, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, numbers, and hyphens. underscores is not allowed.', regex='^[a-zA-Z0-9-]+$')]),
        ),
        migrations.AlterField(
            model_name='workflownodecompile',
            name='key',
            field=models.CharField(help_text='Key 只能包含字母，数字和横杠，不允许空格和下划线', max_length=100, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, numbers, and hyphens. underscores is not allowed.', regex='^[a-zA-Z0-9-]+$')]),
        ),
    ]
