# Generated by Django 5.1.1 on 2024-10-15 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0032_alter_workflownodebody_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflownodebody',
            name='key',
            field=models.CharField(help_text='Key 只能包含字母，数字和横杠，不允许空格和下划线，优先推荐小写字母与横杠', max_length=100, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, numbers, and hyphens. underscores is not allowed.', regex='^[a-zA-Z0-9-]+$')]),
        ),
        migrations.AlterField(
            model_name='workflownodebody',
            name='title',
            field=models.CharField(blank=True, help_text='需要填写，控制输入框的 placeholder', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workflownodebody',
            name='type',
            field=models.CharField(choices=[('Default', 'Default'), ('File', 'File'), ('Textarea', 'Textarea')], default='Default', help_text='Default 使用 jsonSchema 控制用户输入内容，Textarea 使用纯文本框控制用户输入内容，File 为让用户上传文件', max_length=50),
        ),
    ]
