# Generated by Django 5.1.1 on 2024-10-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0034_workflownodebody_select_choices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflownodebody',
            name='type',
            field=models.CharField(choices=[('DEFAULT', 'Default'), ('FILE', 'File'), ('TEXTAREA', 'Textarea'), ('SELECT', 'Select')], default='Default', help_text='Default 使用 jsonSchema 控制用户输入内容，Textarea 使用纯文本框控制用户输入内容，File 为让用户上传文件, Select 为选择框', max_length=50),
        ),
    ]
