# Generated by Django 5.1.2 on 2024-10-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0035_alter_workflownodebody_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflownodebody',
            name='select_choices',
            field=models.JSONField(blank=True, help_text='select_choices 为选择框的选项，为对象列表，包含 name，value 两个字段', null=True),
        ),
        migrations.AlterField(
            model_name='workflownodecompile',
            name='type',
            field=models.CharField(choices=[('File', 'File'), ('String', 'String'), ('Object', 'Object')], max_length=50),
        ),
    ]
