# Generated by Django 5.1.2 on 2024-10-16 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0037_alter_workflownodecompile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflownodecompile',
            name='type',
            field=models.CharField(choices=[('Parameter', 'Parameter'), ('Artifact', 'Artifact')], default='Parameter', help_text='Parameter 为参数，Artifact 为输出文件路径', max_length=50),
        ),
    ]
