# Generated by Django 5.1.2 on 2024-10-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0038_alter_workflownodecompile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
