# Generated by Django 5.1.2 on 2024-10-31 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0039_workflow_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflownode',
            name='minimized',
            field=models.BooleanField(default=False),
        ),
    ]
