# Generated by Django 5.1.2 on 2024-10-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0040_workflownode_minimized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflownodecompile',
            name='source',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workflownodehandle',
            name='label',
            field=models.CharField(blank=True, help_text='Label 控制显示的文本，若为空则显示 key 的大写值', max_length=100, null=True),
        ),
    ]
