# Generated by Django 5.1.2 on 2024-10-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0041_alter_workflownodecompile_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflownodecompile',
            name='script',
            field=models.TextField(max_length=100),
        ),
    ]
