# Generated by Django 5.1.2 on 2024-10-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0042_alter_workflownodecompile_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflownodecompile',
            name='source',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
