# Generated by Django 5.1.2 on 2024-10-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0044_alter_workflownodecompile_script_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflownodecompile',
            name='attachment',
        ),
        migrations.AddField(
            model_name='workflownodecompile',
            name='readable',
            field=models.BooleanField(default=False),
        ),
    ]
