name: Auto-rebase dev on main

on:
  push:
    branches:
      - main
    # 忽略 dev 分支的推送，避免循环触发
    paths-ignore:
      - 'dev/**'

jobs:
  rebase-dev:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 允许强制推送

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev
          # 使用 PAT 以绕过受保护分支的限制
          token: ${{ secrets.DEV_PAT }}
          fetch-depth: 0 # 获取完整提交历史

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Fetch latest main branch
        run: git fetch origin main:main

      - name: Rebase dev onto main (自动冲突解决)
        run: |
          # 执行变基，冲突时自动选择 dev 的代码
          git rebase main || {
            git diff --name-only --diff-filter=U | xargs -I {} git checkout --ours {}
            git add -A
            git rebase --continue
          }

      - name: Force push dev branch
        run: git push origin dev --force
